In [1]:
import numpy as np

In [14]:
r= np.matrix([[-1,-1,-1,-1,0,-1],
            [-1,-1,-1,0,-1,100],
            [-1,-1,-1,0,-1,-1],
            [-1,0,0,-1,0,-1],
            [-1,0,0,-1,-1,100],
            [-1,0,-1,-1,0,100]])
r

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [20]:
q= np.matrix(np.zeros([6,6]))
q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [23]:
gamma = 0.8
initial_state= 1

In [25]:
def available_actions(state):
    current_state_row= r[state,]
    av_act = np.where(current_state_row>=0)[1]
    return av_act

In [28]:
available_actions(initial_state)

array([3, 5], dtype=int64)

In [29]:
current_state_row= r[1,]
current_state_row

matrix([[ -1,  -1,  -1,   0,  -1, 100]])

In [30]:
available_act= available_actions(initial_state)
available_act

array([3, 5], dtype=int64)

In [32]:
# Next avilable action values :
# are returned by the av_act

In [66]:
def sample_next_actions(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action

In [67]:
next_action = int(np.random.choice(available_act,1))
next_action

3

In [68]:
action = sample_next_actions(available_act)

In [69]:
action

5

In [57]:
def update(current_state, action,gamma):
    max_index = np.where(q[action,]==np.max(q[action,]))[1]
    if max_index.shape[0]>1:
        max_index = int(np.random.choice(max_index,size=1))
    else:
        max_index = int(max_index)
    max_value = q[action,max_index]
    q[current_state,action]=r[current_state,action]+gamma*max_value
    


In [70]:
update(initial_state,action,gamma)

In [71]:
max_index = np.where(q[5,] == np.max(q[5,]))[1]
max_index

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [72]:
max_index.shape[0]

6

In [73]:
q/np.max(q)*100

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [75]:
for i in range(10000):
    current_state = np.random.randint(0,int(q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_actions(available_act)
    update(current_state,action,gamma)

print("trained Q matrix")
print(q/np.max(q)*100)

trained Q matrix
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [ ]:
# current_state = 1
# steps = [current_state]

# while current_state!=5:
#     next_step_index = np.where(q[current_state,]==np.max(q[current_state,]))[1]
    
#     if next_step_index.shape[0]>1:
#         next_step_index = int(np.random.choice(next_step_index,index,size=1))
#     else:
#         next_step_index = int(next_step_index)
#     steps.append(next_step_index)
    
# print("selectedPath:")
# print(steps)

In [ ]:
q