In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
social=pd.read_csv("../Datasets/Social_Network_Ads.csv")
social

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

# Spliting Output Data And input Data

In [3]:
X=social.iloc[:,[2,3]].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [4]:
y=social.iloc[:,4].values

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
# Generating Testing and Training Data

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=2)

In [8]:
from sklearn.preprocessing import StandardScaler 
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
X_test

array([[-0.84234932,  0.41749923],
       [-1.61930488, -1.5673008 ],
       [-0.06539376, -0.4712172 ],
       [-0.84234932,  0.18050818],
       [ 1.5856368 ,  0.03238878],
       [ 0.90580069, -1.44880527],
       [-1.42506599,  0.38787535],
       [-0.93946876, -1.0933187 ],
       [ 0.22596457, -0.26385003],
       [-0.1625132 ,  1.69132611],
       [-1.32794654, -1.35993363],
       [-1.52218543, -1.24143811],
       [-0.55099098,  1.42471118],
       [ 0.7115618 ,  0.29900371],
       [-0.25963265, -0.29347391],
       [-0.45387154, -0.76745601],
       [-1.81354377,  0.03238878],
       [ 2.16835347, -0.79707989],
       [ 1.48851736,  0.09163654],
       [-1.13370765, -0.76745601],
       [-0.06539376,  0.26937982],
       [ 0.7115618 , -0.70820825],
       [-0.74522987, -0.20460227],
       [-0.1625132 , -1.06369482],
       [-1.2308271 ,  0.32862759],
       [ 0.7115618 , -1.0933187 ],
       [ 0.7115618 , -1.38955751],
       [ 0.22596457, -0.35272168],
       [ 0.61444235,

In [14]:
from sklearn.ensemble import RandomForestClassifier
cfr=RandomForestClassifier(n_estimators=5,random_state=3)
cfr.fit(X_train,y_train)
pred=cfr.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,pred)
cm

array([[55,  7],
       [ 4, 34]], dtype=int64)

In [18]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,pred))

0.89


In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.89      0.91        62
           1       0.83      0.89      0.86        38

    accuracy                           0.89       100
   macro avg       0.88      0.89      0.88       100
weighted avg       0.89      0.89      0.89       100

