In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("../Datasets/cancer_dataset.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

# Hold Out Cross Validations:

In [4]:
X=df.drop(['diagnosis','id','Unnamed: 32'],axis=1)
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [5]:
y=df['diagnosis']
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [8]:
y.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=5)
print('Train',X_train,y_train,'Test',X_test,y_test)
# we can sometimes use the train size tooo

Train      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
47        13.170         18.66           85.98      534.6          0.11580   
527       12.340         12.27           78.94      468.5          0.09003   
435       13.980         19.62           91.12      599.5          0.10600   
21         9.504         12.44           60.34      273.9          0.10240   
554       12.880         28.92           82.50      514.3          0.08123   
..           ...           ...             ...        ...              ...   
8         13.000         21.82           87.50      519.8          0.12730   
73        13.800         15.79           90.43      584.1          0.10070   
400       17.910         21.02          124.40      994.0          0.12300   
118       15.780         22.91          105.70      782.6          0.11550   
206        9.876         17.27           62.92      295.4          0.10890   

     compactness_mean  concavity_mean  concave points_mea

# LOOCV

In [12]:
from sklearn.model_selection import LeaveOneOut
c=[10,20,30,40,50,60,70,80,90,100]
l=LeaveOneOut()

In [13]:
for X_train,X_test in l.split(c):
    print("%s %s"%(X_train,X_test))

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# K-Fold Cross Validations

In [22]:
from sklearn.model_selection import KFold
x=['a','b','c','d','e','f']
kf=KFold(n_splits=3,shuffle=False,random_state=None)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train,test in kf.split(x):
    print("Train:",train,"Test:",test)

Train: [2 3 4 5] Test: [0 1]
Train: [0 1 4 5] Test: [2 3]
Train: [0 1 2 3] Test: [4 5]


In [25]:
#  it Decresases the  number of Iterations in the Dataset

# Stratified K Fold

In [27]:
from sklearn.model_selection import StratifiedKFold
X=np.array([[10,20],[30,40],[50,60],[70,80],[90,100],[110,120]])
y=np.array([0,0,1,0,1,1])
print(X)
print(y)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]
[0 0 1 0 1 1]


In [28]:
skf=StratifiedKFold(n_splits=3,random_state=None,shuffle=False)

for train_index,test_index in skf.split(X,y):
    print("train:",train_index,"Test:",test_index)
    X_train,X_test=X[train_index],X[test_index]
    y_train,y_test=y[train_index],y[test_index]

train: [1 3 4 5] Test: [0 2]
train: [0 2 3 5] Test: [1 4]
train: [0 1 2 4] Test: [3 5]


In [29]:
print(X_train)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 90 100]]


In [30]:
print(X_test)

[[ 70  80]
 [110 120]]


In [31]:
print(X[train_index])

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 90 100]]


In [32]:
print(y[train_index])

[0 0 1 1]


# Repeated-Random Test Train Split

In [33]:
x=['a','b','c','d','e','f']
from sklearn.model_selection import ShuffleSplit
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
ssplit

ShuffleSplit(n_splits=10, random_state=None, test_size=0.3, train_size=None)

In [34]:
for train,test in ssplit.split(x):
    print("train:",train,"test:",test)

train: [2 3 5 0] test: [1 4]
train: [2 5 4 1] test: [0 3]
train: [4 0 1 5] test: [2 3]
train: [0 4 1 2] test: [3 5]
train: [5 0 3 4] test: [2 1]
train: [3 0 4 2] test: [1 5]
train: [5 2 4 3] test: [0 1]
train: [2 4 0 1] test: [5 3]
train: [4 0 2 1] test: [5 3]
train: [5 0 1 4] test: [2 3]


In [35]:
df.drop(["Unnamed: 32"],axis=1,inplace=True)
X=df.iloc[:,2:]
y=df.iloc[:,1]

In [36]:
y.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [37]:
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [38]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [40]:
X=X.dropna(axis=1)
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [44]:
# Cross_val_score()
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
model=DecisionTreeClassifier()
score=cross_val_score(model,X,y,cv=10)
score
# CV meaning testing numbers:

array([0.9122807 , 0.85964912, 0.92982456, 0.85964912, 0.94736842,
       0.89473684, 0.87719298, 0.94736842, 0.9122807 , 0.98214286])

In [45]:
score=cross_val_score(model,X,y,cv=20)
score

array([1.        , 0.89655172, 0.89655172, 0.82758621, 0.93103448,
       0.93103448, 0.79310345, 0.96551724, 0.93103448, 0.92857143,
       0.92857143, 0.85714286, 1.        , 0.92857143, 1.        ,
       0.89285714, 0.96428571, 0.82142857, 1.        , 0.96428571])

In [47]:
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=100)
dt=DecisionTreeClassifier()
dtmode1=dt.fit(X_train,y_train)

In [48]:
dt.score(X_train,y_train)

1.0

In [49]:
hoo_result=dtmode1.score(X_test,y_test)
print("the Accuracy score for Hold Out Method: ",hoo_result)

the Accuracy score for Hold Out Method:  0.9473684210526315


In [50]:
# K-Fold Method

In [55]:
kf=KFold(n_splits=5)
kfold_score=cross_val_score(dt,X,y,cv=kf)
print("K fold score:",kfold_score)
kfold_score_mean=kfold_score.mean()
print("K fold Score Mean:",kfold_score_mean)
print("K fold Max score:",max(kfold_score))
print("K fold min score:",min(kfold_score))

K fold score: [0.89473684 0.9122807  0.94736842 0.89473684 0.88495575]
K fold Score Mean: 0.9068157118459865
K fold Max score: 0.9473684210526315
K fold min score: 0.8849557522123894


In [57]:
kf2=KFold(n_splits=5)
acc_score_kfold=[]
for train_ind,test_ind in kf2.split(X,y):
    X_train,X_test=X.iloc[train_ind,:],X.iloc[test_ind,:]
    y_train,y_test=y[train_ind],y[test_ind]
    
    dt.fit(X_train,y_train)
    pred_values=dt.predict(X_test)
    
    acc=accuracy_score(pred_values,y_test)
    acc_score_kfold.append(acc)
avg_acc_score= sum(acc_score_kfold)/5
print("accuracy of each fold:{}".format(acc_score_kfold))
print("avg accuracy:{}".format(avg_acc_score))

accuracy of each fold:[0.868421052631579, 0.8947368421052632, 0.9473684210526315, 0.9298245614035088, 0.8849557522123894]
avg accuracy:0.9050613258810742


In [59]:
# stratified k fold Method

In [62]:
skfold=StratifiedKFold(n_splits=10)
skfold_score = cross_val_score(dt,X,y,cv=skfold)
print("the Accuracy of Stratified k -fold method is :",skfold_score)
skfold_score_mean=skfold_score.mean()
print("the average of stratified k fold with 10 folds is :",skfold_score_mean)

the Accuracy of Stratified k -fold method is : [0.92982456 0.89473684 0.9122807  0.85964912 0.92982456 0.9122807
 0.87719298 0.94736842 0.92982456 0.875     ]
the average of stratified k fold with 10 folds is : 0.9067982456140351


In [63]:
# Leave One Out method

In [64]:
loocv=LeaveOneOut()
loocv_score=cross_val_score(dt,X,y,cv=loocv)
print("the accuracy of LOOCV: ",loocv_score)
loocv_score_mean=loocv_score.mean()
print("the accuracy average is :",loocv_score_mean)

the accuracy of LOOCV:  [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [65]:
# DIGITS DATA

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [70]:
from sklearn.datasets import load_digits
digits=load_digits()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3,random_state=4)

In [72]:
lr=LogisticRegression(solver='liblinear')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [73]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.5814814814814815

In [74]:
rf=RandomForestClassifier(n_estimators=10)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [75]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [81]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
scores_logistic=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=10),X_train,X_test,y_train,y_test))

In [82]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [84]:
    for j in range(3):
        print(scores_logistic[j])
        print(scores_svm[j])
        print(scores_rf[j])

0.8948247078464107
0.3806343906510851
0.8781302170283807
0.9532554257095158
0.41068447412353926
0.9115191986644408
0.9098497495826378
0.5125208681135225
0.9015025041736227


In [86]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [87]:
scores_rf

[0.8781302170283807, 0.9115191986644408, 0.9015025041736227]

In [88]:
# Parameter Tuning using K fold cross Validation

In [92]:
score1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=10)
np.average(score1)

0.8725946617008068

In [93]:
score2=cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=10)
np.average(score2)

0.9115456238361265

In [94]:
score3=cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target,cv=10)
np.average(score3)

0.9354531346989449

In [95]:
score4=cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=10)
np.average(score4)

0.942129112352576

In [96]:
score5=cross_val_score(RandomForestClassifier(n_estimators=500),digits.data,digits.target,cv=10)
np.average(score5)

0.9499130974549969

In [97]:
score6=cross_val_score(RandomForestClassifier(n_estimators=500),digits.data,digits.target,cv=100)
np.average(score6)

0.9777124183006535